name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0' 

    - name: Install dependencies
      run: cd GitWorkflow; dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests
      run: cd ../Test; dotnet test --no-build --verbosity normal
